stages:
  - test
  - build
  - deploy

variables:
  MYSQL_DATABASE: "dashboard"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "root"
  MYSQL_HOST: "mysql"
  DJANGO_DB_ENGINE: "mysql"
  DJANGO_DB_NAME: $MYSQL_DATABASE
  DJANGO_DB_USER: $MYSQL_USER
  DJANGO_DB_PASSWORD: $MYSQL_PASSWORD
  DJANGO_DB_HOST: $MYSQL_HOST
  DJANGO_DB_PORT: "3306"
  CI_REGISTRY_IMAGE: "gitlab.paris-digital-lab.com:5050/centralesupelec-fall2023-p2/codingcoach"
  REGISTRY_IMAGE_DJANGO: $CI_REGISTRY_IMAGE/django
  REGISTRY_IMAGE_MYSQL: $CI_REGISTRY_IMAGE/mysql

default:
  image: ubuntu:22.04

services:
  - mysql:8.0

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - apt -y update
  - apt -y install apt-utils
  - apt -y install net-tools python3 python3-pip mysql-client libmysqlclient-dev
  - pip3 install -r webserver/requirements.txt

test:
  stage: test
  script:
    - echo "TESTS"

build:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check
    - docker-compose build
    - docker push $REGISTRY_IMAGE_DJANGO
    - docker push $REGISTRY_IMAGE_MYSQL

deploy:
  stage: deploy
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE

# only:
#   - cicd
