version: "3.8"

services:
  django:
    build:
      context: ./dashboard
      dockerfile: DockerfileDjango
    networks:
      - codingcoachNet
    ports:
      - 8000:8000

  node:
    build:
      context: ./node
      dockerfile: DockerfileNode
    networks:
      - codingcoachNet

  
   
  dev:
    build:
      context: ./
      dockerfile: .devcontainer/dockerfileDev
    command: sleep infinity
    networks:
      - codingcoachNet
    volumes:
      - dev-data:/app
  
  mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: root
    #   MONGO_INITDB_DATABASE: dashboard
    networks:
      - codingcoachNet
    ports:
      - 27017:27017
  




    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  
    

networks:
  codingcoachNet:
volumes:
  dev-data:
  mongodb-data: