version: "3.8"

services:
  django:
    command: python3 manage.py makemigrations
    build:
      context: ./webserver
      dockerfile: DockerfileDjango
    networks:
      - codingcoachNet
    ports:
      - 80:80

  mysql:
    restart: unless-stopped
    build: 
      context: ./.devcontainer 
      dockerfile: DockerfileMysql
    networks:
      - codingcoachNet
    ports:
      - 3306:3306


networks:
  codingcoachNet:

volumes:
  dev-data:
  mysql-data:
