version: "3.8"

services:
  django:
    build:
      context: ./webserver
      dockerfile: DockerfileDjango
    networks:
      - codingcoachNet
    ports:
      - 8000:8000
    environment:
      - DB_ENGINE=mysql
      - DB_NAME=dashboard
      - DB_USERNAME=root
      - DB_PASS=root
      - DB_HOST=mysql
      - DB_PORT=3306

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/DockerfileDev
    command: sleep infinity
    environment:
      - DB_ENGINE=mysql
      - DB_NAME=dashboard
      - DB_USERNAME=root
      - DB_PASS=root
      - DB_HOST=mysql
      - DB_PORT=3306
    networks:
      - codingcoachNet
    volumes:
      - dev-data:/app

  mysql:
    build:
      context: ./
      dockerfile: .devcontainer/DockerfileMysql
    networks:
      - codingcoachNet
    ports:
      - 3306:3306


networks:
  codingcoachNet:

volumes:
  dev-data:
  mysql-data:
