version: "3.8"

services:
  django:
    build:
      context: ./dashboard
      dockerfile: DockerfileDjango
    networks:
      - my-network
    ports:
      - "8000:8000"

  node:
    build:
      context: ./node
      dockerfile: DockerfileNode
    networks:
      - my-network

  
   
  dev:
    build:
      context: ./
      dockerfile: .devcontainer/dockerfileDev
    command: sleep infinity
    networks:
      - my-network
    volumes:
      - dev-data:/app
  
   db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

    # Uncomment to change startup options
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dashboard
    ports:
      - "27017:27017"


    # Add "forwardPorts": ["27017"] to **devcontainer.json** to forward MongoDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)


  
    

networks:
  my-network:
volumes:
  dev-data:
  mongodb-data: