version: "3.8"

services:
  django:
    build:
      context: ./dashboard
      dockerfile: DockerfileDjango
    networks:
      - codingcoachNet
    ports:
      - 8000:8000

  node:
    build:
      context: ./node
      dockerfile: DockerfileNode
    networks:
      - codingcoachNet

  dev:
    build:
      context: ./
      dockerfile: .devcontainer/DockerfileDev
    command: sleep infinity
    networks:
      - codingcoachNet
    volumes:
      - dev-data:/app

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard
    networks:
      - codingcoachNet
    ports:
      - 3306:3306


networks:
  codingcoachNet:

volumes:
  dev-data:
  mysql-data:
