version: '3.8'

services:
  django:
    build:
      context: ./webserver
      dockerfile: DockerfileDjango
    ports:
      - "8000:8000"  # Adjust the port if necessary
    depends_on:
      - mysql
    command: >
      bash -c "
        sleep 5 && 
        echo 'MIGRATE' && 
        python3 manage.py makemigrations &&
        python3 manage.py migrate  && echo 'run' && 
        python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_ENGINE=mysql
      - DB_NAME=dashboard
      - DB_USERNAME=root
      - DB_PASS=root
      - DB_HOST=mysql
      - DB_PORT=3306

  mysql:
    image: mysql:latest
    command: mysqld        
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard
    ports:
      - 3306:3306