# Generated by Django 4.1.12 on 2023-12-06 12:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabAccessRepo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('projectName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('moodLevel', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('branchNumber', models.IntegerField()),
                ('branchBehindMax', models.IntegerField()),
                ('branchAheadMax', models.IntegerField()),
                ('lastPrTime', models.DateTimeField(blank=True, null=True)),
                ('commitQuality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255)),
                ('gitlabRepo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gitlabAccess', to='dashboard.gitlabaccessrepo')),
                ('moods', models.ManyToManyField(blank=True, related_name='moods', to='dashboard.teammood')),
                ('repos', models.ManyToManyField(blank=True, related_name='repos', to='dashboard.teamrepo')),
                ('users', models.ManyToManyField(blank=True, related_name='teams', to='dashboard.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='CoachCas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(blank=True, related_name='coaches', to='dashboard.teamtable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, related_name='teams', to='dashboard.teamtable')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
