# Generated by Django 4.1.12 on 2023-11-22 09:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255, unique=True)),
                ('teamGitlabAccessToken', models.CharField(max_length=255)),
                ('coachs', models.ManyToManyField(related_name='coachs', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='teams', to='dashboard.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('branchNumber', models.IntegerField()),
                ('branchBehindMax', models.IntegerField()),
                ('branchAheadMax', models.IntegerField()),
                ('lastPrTime', models.DateTimeField(blank=True, null=True)),
                ('commitQuality', models.IntegerField()),
                ('teams', models.ManyToManyField(related_name='repos', to='dashboard.teamtable')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('moodLevel', models.IntegerField()),
                ('message', models.TextField()),
                ('teams', models.ManyToManyField(related_name='moods', to='dashboard.teamtable')),
            ],
        ),
    ]
