# Generated by Django 4.1.12 on 2023-11-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtable',
            name='teamName',
            field=models.CharField(max_length=255),
        ),
    ]
