# Generated by Django 4.1.12 on 2023-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_teamtable_coachs_coach_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitlabAccessRepo',
            fields=[
                ('token', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('projectName', models.CharField(max_length=255)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
