# Generated by Django 4.1.12 on 2023-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_teamtable_teamname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
