# Generated by Django 4.1.12 on 2023-11-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('teamId', models.AutoField(primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=255, unique=True)),
                ('teamGitlabAccessToken', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(blank=True, related_name='teams', to='dashBoard.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('branchNumber', models.IntegerField()),
                ('branchBehindMax', models.IntegerField()),
                ('branchAheadMax', models.IntegerField()),
                ('lastPrTime', models.DateTimeField(blank=True, null=True)),
                ('commitQuality', models.IntegerField()),
                ('teams', models.ManyToManyField(related_name='repos', to='dashBoard.teamtable')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('moodLevel', models.IntegerField()),
                ('message', models.TextField()),
                ('teams', models.ManyToManyField(related_name='moods', to='dashBoard.teamtable')),
            ],
        ),
        migrations.CreateModel(
            name='CoachTable',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('teams', models.ManyToManyField(blank=True, related_name='teams', to='dashBoard.teamtable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
