# Generated by Django 4.1.12 on 2023-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachtable',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='teams', to='dashboard.teamtable'),
        ),
    ]
